# Sensitivity test

In [1]:
notebook_name = "sensitivity_test"

In [2]:
from sensitivity_test import *

In [3]:
import warnings
warnings.filterwarnings("ignore")
import matplotlib as mpl
mpl.rcParams['font.family'] = 'sans-serif'
# 優先順位を Helvetica → Arial の順に設定（必要なら他のフォントを追加）
mpl.rcParams['font.sans-serif'] = ['Helvetica', 'Arial']    

from param_test import set_sensitive_param, set_fix_param

In [4]:
def display_dict(param_dict):
    df = pd.DataFrame(dict([k, pd.Series(v)] for k, v in param_dict.items()))

    display(df)

## あらかじめ絞れるパラメータ

### temperature of sea surface of initial evaporation

Nakamura et al. 2008 GRL　Fig. 1より、typicalな　SST frontは5-15度くらい。その周辺でstorm track活動が活発になると考える。 -> 蒸発起源SST

In [5]:
param_fix_dict_org = {
    "temp_sea_init_list":[ [5, 10, 15]]    ,
    "BOOL_REEVAP": False, # 十分湿っている雲には返らない
    "temp_surf": [0],
}
display_dict(param_fix_dict_org)

  temp_sea_init_list  BOOL_REEVAP  temp_surf
0        [5, 10, 15]        False          0

## Tuningにより感度が低いと判断されたパラメータ

In [6]:
param_fix_dict_HDO = set_fix_param("HDO")
param_fix_dict_H218O = set_fix_param("H218O")

display_dict(param_fix_dict_HDO)
display_dict(param_fix_dict_H218O)

,prcp_perday,p_btm,p_top,rh_surf,dt,ALPHA_RY_MODE,h_air,surface_wind,temp_air_init_list
0,2,700,400,0.75,0.5,eff,1,6.5,"[5, 10, 15]"

,prcp_perday,p_btm,p_top,rh_surf,dt,ALPHA_RY_MODE,h_air,surface_wind,temp_air_init_list
0,2,700,400,0.75,0.5,eff,1,6.5,"[5, 10, 15]"

## 感度実験の必要なパラメータ

In [7]:
param_test_dict_HDO = set_sensitive_param("HDO")
param_test_dict_H218O = set_sensitive_param("H218O")

display_dict(param_test_dict_HDO)
display_dict(param_test_dict_H218O)

   resub_factor  prcp_duration CLOUD_AGING  delta_q_surf  temp_air_fin
0           0.2           0.25        True        -120.0         -20.0
1           0.5           1.00       False        -100.0         -10.0
2           NaN           3.00         NaN           NaN           NaN

   resub_factor  prcp_duration CLOUD_AGING  delta_q_surf  temp_air_fin
0           0.2           0.25        True         -15.0         -20.0
1           0.5           1.00       False         -12.5         -10.0
2           NaN           3.00         NaN           NaN           NaN

In [8]:
fig_title="Sensitivity test_HDO"
param_test_dict =  param_test_dict_HDO
param_fix_dict =  param_fix_dict_org | param_fix_dict_HDO
ylim = (-200, -80)

run_sensitivity_analysis(
    param_test_dict=param_test_dict,
    param_fix_dict=param_fix_dict,
    title=fig_title,
    iso_model_dir=iso_model_dir,
    subplot_hnum_max=6,
    xlim = (0, 10),
    ylim = ylim,
    notebook_name=notebook_name,
    GENERATE_CSV = False
    
)

Error in combination <Future at 0x16449ed10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644ae810 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644aee10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644aedd0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644aefd0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644af150 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644af2d0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644af450 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644af5d0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644af790 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644af910 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644afa90 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644afc10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644afd90 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644aff10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b00d0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0250 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b03d0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0550 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0710 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0910 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0b10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0d10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b0f10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1110 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1310 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1510 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1710 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1910 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1b10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1d10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b1f10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644b2110 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x16449ff10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a3890 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x16448bbd0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a1610 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x16449f390 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a0b10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a0c90 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1643e4390 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644ad7d0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a3ad0 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644ad250 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a1f90 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644a0310 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1643fdb10 state=finished raised TypeError>: can only concatenate list (not "float") to list
Error in combination <Future at 0x1644ac350 state=finished raised TypeError>: can only concatenate list (not "float") to list

File saved as '/Users/kanon/Work/IsoFracPy/analysis/figures/Sensitivity_test_HDO.png'.
Sensitivity analysis completed.

- モデルでは、`temp_air_fin`が低すぎる（あるいは上空で生成される同位体比が低すぎる）
- モデルでは、昇華効率`f`が大きすぎる
- モデルでは、降水量`prcp_perday`が大きすぎる

あるいは、下がりトレンドが続いてしまうのは、雲が入れ替わらないから。